# This section defines the default nextest profile. Custom profiles are layered
# on top of the default profile.
[profile.default]
# The set of tests run by `cargo nextest run` by default.
default-filter = "all()"

# This profile is selected by `cargo-brazil-on-test`.
[profile.ci]
# run all tests
default-filter = 'all()'

# Do not cancel the test run on the first failure.
fail-fast = false

# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"

# Will terminate the test after `terminate-after` * `period` has passed.
slow-timeout = { period = "60s", terminate-after = 2 }
